name: Check Links

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lycheeverse/lychee-action@v1.5.4
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :wave: Hi @${{ github.event.pull_request.user.login }}! :wave:
            Thanks for your pull request. I've run [lychee](https://github.com/lycheeverse/lychee)
            on the repository and it reported some broken links.
            ${LYCHEE_OUTPUT}
